title: Fariha Sultana Rini
#logo: /assets/img/headshot_circle.png
#description: https://tinyurl.com/farihasultanarini
linkedin:"https://tinyurl.com/farihasultanarini"
"https://somikoron.ai/"
#show_downloads: true
theme: jekyll-theme-minimal
